/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		AButton: typeof import('ant-design-vue/es')['Button'];
		AForm: typeof import('ant-design-vue/es')['Form'];
		AFormItem: typeof import('ant-design-vue/es')['FormItem'];
		AInput: typeof import('ant-design-vue/es')['Input'];
		AInputPassword: typeof import('ant-design-vue/es')['InputPassword'];
		HelloWorld: typeof import('./src/components/HelloWorld.vue')['default'];
		IssuseAndPr: typeof import('./src/components/IssuseAndPr/index.vue')['default'];
		RouterLink: typeof import('vue-router')['RouterLink'];
		RouterView: typeof import('vue-router')['RouterView'];
	}
}
